### ISSUE TITLE
Page limitation

### ISSUE THREAD

**Issue by suntong** [andrew-d/goscrape#6]
How to set page limitation?

Sometimes we don't want to scrap till that 99+ pages, but only the first few. 

So it is nice to have page limitation defined when scraping. 

Thanks

**Comment by andrew-d** [comment]
Hi there!  You can set the `MaxPages` option in `ScrapeOptions`, like [here](https://github.com/andrew-d/goscrape/blob/dc9bbbfc77d64938e8690e3a514c49a2ec839383/_examples/scrape_hn.go#L36).

**Comment by suntong** [comment]
<embarrassed> that's the only example that I haven't skim through. :( Thank!
